spring:
  profiles:
    active: native # look locally ?
  application:
    name: configserver
  cloud:
    config:
      name: configserver
      server:
        native:
          search-locations:
            - classpath:/config/

server:
  port: 8888 # 8888 conventional port
