server:
  port: 8080

# database config
spring:
  application:
    name: user
  datasource:
    username: 'application'
    url: jdbc:postgresql://localhost:5432/user
    password: 'groan-unsnarl-hedgehog-incubus-sate-JAW'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl_auto: update
      show-sql: true

# cloud config todo: port
spring.cloud.config.uri: http://localhost:0000

# eureka service registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka