services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: groan-unsnarl-hedgehog-incubus-sate-JAW
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

# Master Password: saloon-CUPRIC-stridden-commence-wadi-palisade
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: service@mustafasalem.com
      PGADMIN_DEFAULT_PASSWORD: contrary-sushi-sextuple-jab-infract-BING
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
    - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # Rabbit MQ
  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    ports: # host:container
      - 5672:5672 # microservices
      - 15672:15672 # management console
    # todo: networks:

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: