spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: graphical-user-interface
          uri: lb://GRAPHICAL-USER-INTERFACE
          predicates:
            - Path=/**
server:
  port: 80 # default HTTP port
# eureka service registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka